name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: | 
          sudo -i

          # Start by installing Node.js 20:
          
          curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n
          bash n 20
          
          # Node.js 20 is now at /usr/local/bin/node, but glibc 2.28 is missing:
          # node: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by node)
          # /usr/local/bin/node: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/bin/node)
          
          # Build and install glibc 2.28:
          apt install -y gawk
          cd ~
          wget -c https://ftp.gnu.org/gnu/glibc/glibc-2.28.tar.gz
          tar -zxf glibc-2.28.tar.gz
          cd glibc-2.28
          ./configure --prefix=/opt/glibc-2.28
          make -j 4 # Use all 4 Jetson Nano cores for much faster building
          make install
          cd ..
          rm -fr glibc-2.28 glibc-2.28.tar.gz
          
          # Patch the installed Node.js 20 to work with /opt/glibc-2.28 instead:
          apt install -y patchelf
          patchelf --set-interpreter /opt/glibc-2.28/lib/ld-linux-aarch64.so.1 --set-rpath /opt/glibc-2.28/lib/:/lib/aarch64-linux-gnu/:/usr/lib/aarch64-linux-gnu/ /usr/local/bin/node
          
          # Et voilà:
          node --version
          v20.8.0
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py

          echo "## Model metrics" > report.md
          cat metrics.txt >> report.md

          echo "## Data viz" >> report.md
          cml-publish feature_importance.png --md >> report.md
          cml-publish residuals.png --md >> report.md

          cml-send-comment report.md
